In [1]:
import pandas as pd

In [2]:
latents_csv = pd.read_csv("/mnt/d/lding/CLS_GitHub/SubCellAE/results/ae_run/baseline_AE/latents.csv")

In [8]:
latents_csv

,filename,filepath,condition,condition_name,group,split,recon_mse,mean_intensity,norm_mse,z_0,z_1,z_2,z_3,z_4,z_5,z_6,z_7,annotation_label,annotation_label_name
0,control_f0001x0112y0496ps32.tif,/mnt/d/lding/FA/analysis_results/FA_ML_Annabel...,0,control,control_f0001,train,0.003637,0.071482,0.050875,0.329768,0.025340,-1.210286,-0.216079,-0.262456,-0.265051,-0.932593,-0.287198,-1,NaN
1,control_f0001x0144y0464ps32.tif,/mnt/d/lding/FA/analysis_results/FA_ML_Annabel...,0,control,control_f0001,train,0.004671,0.134406,0.034753,-1.365138,0.207984,0.528708,1.785719,-1.069953,0.776651,1.428365,1.010483,-1,NaN
2,control_f0001x0144y0496ps32.tif,/mnt/d/lding/FA/analysis_results/FA_ML_Annabel...,0,control,control_f0001,train,0.005739,0.085470,0.067141,0.610593,-0.039426,-0.705854,-0.538730,-0.540438,-0.286961,0.099085,-0.028024,-1,NaN
3,control_f0001x0176y0464ps32.tif,/mnt/d/lding/FA/analysis_results/FA_ML_Annabel...,0,control,control_f0001,train,0.004524,0.125730,0.035980,-1.188515,0.870389,0.329237,2.342345,-1.282174,0.989440,0.646282,1.624777,-1,NaN
4,control_f0001x0176y0496ps32.tif,/mnt/d/lding/FA/analysis_results/FA_ML_Annabel...,0,control,control_f0001,train,0.007288,0.114207,0.063811,-0.177030,0.130359,0.025572,0.074563,-0.101450,-0.087927,0.374926,-0.188401,-1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23651,ycomp_f0038x1040y0400ps32.tif,/mnt/d/lding/FA/analysis_results/FA_ML_Annabel...,1,ycomp,ycomp_f0038,val,0.012046,0.103061,0.116880,-0.365726,0.327522,-0.289241,-0.161243,-0.262460,-0.034774,0.667798,-0.000546,-1,NaN
23652,ycomp_f0038x1040y0432ps32.tif,/mnt/d/lding/FA/analysis_results/FA_ML_Annabel...,1,ycomp,ycomp_f0038,val,0.018458,0.113250,0.162981,0.414339,-0.365371,-0.340475,0.276209,0.849913,0.758792,-0.158968,0.678217,-1,NaN
23653,ycomp_f0038x1072y0176ps32.tif,/mnt/d/lding/FA/analysis_results/FA_ML_Annabel...,1,ycomp,ycomp_f0038,val,0.012230,0.084154,0.145328,0.555309,-0.301931,0.286155,0.989329,0.406104,-0.164570,-0.595984,0.101644,-1,NaN
23654,ycomp_f0038x1072y0208ps32.tif,/mnt/d/lding/FA/analysis_results/FA_ML_Annabel...,1,ycomp,ycomp_f0038,val,0.010841,0.083843,0.129302,0.606434,-0.838852,0.205575,0.622535,0.415686,-0.332768,-0.154272,0.100283,-1,NaN
23655,ycomp_f0038x1072y0336ps32.tif,/mnt/d/lding/FA/analysis_results/FA_ML_Annabel...,1,ycomp,ycomp_f0038,val,0.023913,0.127176,0.188030,0.877936,-1.197559,0.486233,1.009997,0.162090,0.409561,-0.346412,-0.444612,-1,NaN

In [6]:
label_csv =pd.read_csv("/mnt/d/lding/FA/analysis_results/labelling/paxdata_paxpatch_batch1and2_combined_labels.csv")

In [7]:
label_csv

,unique_ID,crop_img_filename,group,group_ID,Position,classification
0,control-f0001x0592y0560ps32.tif,f0001x0592y0560ps32.tif,control,0,Cell Body,No adhesion
1,control-f0001x0688y0848ps32.tif,f0001x0688y0848ps32.tif,control,0,Lamella,No adhesion
2,control-f0001x0592y0592ps32.tif,f0001x0592y0592ps32.tif,control,0,Cell Body,No adhesion
3,control-f0001x0368y0528ps32.tif,f0001x0368y0528ps32.tif,control,0,Cell Periphery/other,No adhesion
4,control-f0001x0592y0528ps32.tif,f0001x0592y0528ps32.tif,control,0,Cell Periphery/other,No adhesion
...,...,...,...,...,...,...
1335,ycomp-f0034x0272y0240ps32.tif,f0034x0272y0240ps32.tif,ycomp,1,Lamella,Nascent Adhesion
1336,ycomp-f0035x0624y0976ps32.tif,f0035x0624y0976ps32.tif,ycomp,1,Lamella,Nascent Adhesion
1337,ycomp-f0035x0496y0688ps32.tif,f0035x0496y0688ps32.tif,ycomp,1,Cell Body,No adhesion
1338,ycomp-f0035x0720y0848ps32.tif,f0035x0720y0848ps32.tif,ycomp,1,Cell Protruding Edge,Nascent Adhesion
1339,ycomp-f0035x0688y0368ps32.tif,f0035x0688y0368ps32.tif,ycomp,1,Cell Periphery/other,No adhesion